name: Android Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: sudo apt-get update && sudo apt-get install -y zip unzip
      - run: docker run --rm -v "$PWD/jdv-app":/work -w /work kivy/buildozer:latest buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: jdv-app
          path: jdv-app/bin/*